ignored:
  - DL3002 # Last user should not be root.
  - DL3008 # Pin versions in apt get
  - DL3013 # Pin versions in pip
  - DL3016 # Pin versions in npm
  - DL3018 # Pin versions in apk add
  - DL4001 # Either use Wget or Curl but not both.
