version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  app:
    image: punct_app:e2e
    environment:
      FRONTEND_URL: http://localhost
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: production
    volumes:
      - e2e-socket-data:/myapp/tmp/sockets
    depends_on:
      - db

  web:
    image: punct_web:e2e
    volumes:
      - e2e-socket-data:/myapp/tmp/sockets
    ports:
      - 80:80
    depends_on:
      - app

  # cypress:
  #   image: punct_cypress:latest
  #   depends_on:
  #     - web
  #   environment:
  #     CYPRESS_baseUrl: http://web
  #     VUE_APP_API_URL: http://web/api/
  #   command: yarn test:e2e --url http://web:80/ --headless
  #   volumes:
  #     - frontend/tests/e2e:/myapp/tests/e2e
  #     # - ./e2e/cypress:/app/cypress
  #     # - ./e2e/cypress.json:/app/cypress.json

volumes:
  e2e-socket-data:

# コマンド docker-compose -f docker-compose.e2e.yml up
