inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "db/schema.rb"
    - "config/puma.rb"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.6.5
  NewCops: enable

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# ネストが深すぎる
BlockNesting:
  Max: 5

# クラスの行数が多すぎる
ClassLength:
  Enabled: false

# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
CyclomaticComplexity:
  Enabled: false

# 例外を抑制している
SuppressedException:
  Enabled: false

# 行が長すぎる
LineLength:
  Enabled: false

# メソッドの行数が多すぎる
MethodLength:
  Enabled: false

# 引数の数が多すぎる
ParameterLists:
  Max: 12

# ブロック内の長さ
Metrics/BlockLength:
  Enabled: false

# {}を複数行で使う
BlockDelimiters:
  Enabled: false
