FROM node:12.18.0-alpine as e2e-build-stage
WORKDIR /myapp
ENV TZ Asia/Tokyo
ENV VUE_APP_API_URL http://web/api/

COPY frontend/package.json frontend/yarn.lock /myapp/
RUN yarn install

COPY frontend /myapp
RUN yarn build

FROM nginx:1.19.0-alpine
RUN mkdir /myapp
COPY --from=e2e-build-stage /myapp/dist /myapp/public

RUN rm -f /etc/nginx/conf.d/*
COPY nginx/nginx.conf /etc/nginx/conf.d/myapp.conf

# コマンド docker buildx build -t punct_web:e2e --target e2e -f nginx/Dockerfile .
